codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        informational: true

comment:
  layout: "reach"
  require_changes: true

github_checks:
  annotations: false
