name: Sync metadata and push on changes
on:
  push:
    branches: [main]

jobs:
  sync:
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.COMPAS_GITHUB_TOKEN }}

      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Run sync
        run: |
          npm install
          npx compas run syncMetadata

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore(sync): sync generated doc files"
